### ISSUE TITLE
clickhouse playground not working 

### ISSUE THREAD

**Issue by mayank-pant** [ClickHouse/clickhouse-playground#17]
https://play.clickhouse.com
Cant reach page is coming up ?

**Comment by DerekChia** [comment]
Works well for https://play.clickhouse.com/

<img width="344" alt="image" src="https://user-images.githubusercontent.com/1457728/186577690-f5661220-ed52-4ffd-b606-cf61cc932846.png">


and for https://play.clickhouse.com/play

<img width="343" alt="image" src="https://user-images.githubusercontent.com/1457728/186577783-5a724829-d587-483e-b7b8-dd12ee6ebe07.png">
